# Generated by Django 6.0.4 on 2026-06-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, unique=True)),
                ('TotalSeats', models.PositiveIntegerField(default=0)),
                ('EventDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.TimeField()),
                ('RegisteredEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventAPI.event')),
                ('RegisteredUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventAPI.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('RegisteredUser', 'RegisteredEvent'), name='register_once_constraint')],
            },
        ),
    ]
